### ISSUE TITLE
Améliorer le masque utilisé pour la date de naissance

### ISSUE THREAD

**Issue by nesk** [LAB-MI/deplacement-covid-19#1]
Je pense qu'il y aurait moyen d'améliorer le comportement du masque sur la date de naissance, on ne peut pas effacer facilement les données.

Il existe déjà des outils bien conçus pour ce genre de chose, peut-être qu'on pourrait se servir de [Inputmask](https://github.com/RobinHerbots/Inputmask) par exemple ?

![out](https://user-images.githubusercontent.com/817508/78588758-75a14f00-783f-11ea-983a-7998453fd210.gif)

**Comment by philippeBron** [comment]
Merci pour cette proposition.
Nous avons corrigé la saisie et le contrôle du champ date de naissance dans la version 1.1.0 par une autre méthode qui ne nécessitait pas l'utilisation d'un autre composant.

**Comment by nesk** [comment]
C'est nettement mieux, merci :)
