### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by Benew** [LAB-MI/deplacement-covid-19#101]
Une guideline serait la bienvenue. 
On voit que toutes les PRs sont fermées et jamais mergees. Ça ne donne pas très envie de contribuer.
Est-ce du à une volonté de ne pas accepter les contributions ou juste une limitation technique due par exemple au fait que ce repo le soit qu’un clone du repo de travail?

**Comment by infosteph** [comment]
Bonjour, Effectivement ce repo n'est qu'un clone d'un repo de travail. Vous avez raison sur l'existence d'une guideline.

**Comment by infosteph** [comment]
Bonjour @Benew , Nous avons ajouté une guideline. Bien cordialement,
