### ISSUE TITLE
PDF généré sans motif sélectionné

### ISSUE THREAD

**Issue by Stis** [LAB-MI/deplacement-covid-19#113]
Bonjour.

Sous Android 10, site épinglé en webapp via Chrome.
Sur la 1.1.3

Taper sur Générer mon attestation vérifie bien chacun des champs mais finira par générer un PDF même si aucun motif n'a été sélectionné.

**Comment by BenoitAnastay** [comment]
C'est normal,
Il est possible de ne mettre que son nom et don adresse et compléter en manuscrit

**Comment by Stis** [comment]
Il est vrai que je n'ai pensé qu'à l'utilisation mobile du générateur.
Je clos donc ce souci qui n'en pas tout à fait un... même s'il reste la possibilité dans la précipitation de sortir avec une attestation incomplète.
A voir si on retourne en confinement.
