### ISSUE TITLE
Autre : suggestion application StopCovid

### ISSUE THREAD

**Issue by StopCovidFR** [LAB-MI/deplacement-covid-19#115]
Bonjour,

J'aimerai vous soumettre une suggestion concernant l'application StopCovid.
Etant donné que le Bluetooth pose problème, il y a, je pense, une solution alternative réalisable et disponible pour l'ensemble des smartphones sans restriction.

1. L'utilisateur ouvre un point d'accès wifi sur son téléphone ( avec mot de passe )
2. L'utilisateur laisse donc le Wifi ouvert
3. L'application StopCovid enregistre le **SSID** du réseau wifi de l'utilisateur, et, scan en **permanence** les réseaux à proximité
4. Ainsi, si un utilisateur se retrouve infecté, il suffira d'observer, dans la base de données StopCovid, qui a croisé l'utilisateur

.

Si vous avez besoin de quoi que ce soit,
ce serait avec plaisir.

Cordialement.

**Comment by MacKentoch** [comment]
Bonjour,

Cette suggestion concerne l'application mobile et non ce repo si je ne me trompe pas?
Je ne trouve pas le repo de cette application.
Est elle aussi open source?

**Comment by StopCovidFR** [comment]
Hello,

Exacte. Et non , pas que je sache.
Mais étant donné que c'est l' "Incubateur du ministère de l'intérieur" , et que cette APP est lié a la gestion du coronavirus, j'ai décidé de poster ici.

Sinon je suis ouvert à poster ailleurs... si ailleurs existe :)

**Comment by vboucard** [comment]
aux dernières nouvelles, c'est capgemini qui va développer l'appli et lunabee studio

https://www.inria.fr/fr/stopcovid

**Comment by infosteph** [comment]
Bonjour,
La réalisation de l'application StopCovid ne relève effectivement pas de la responsabilité de l'incubateur du ministère de l'Intérieur. A notre connaissance, il n'existe pas (encore) de dépôt pour cette application. 
Le Gouvernement français ayant confié à l'Inria le pilotage opérationnel du projet, nous vous invitons à contacter cet institut https://inria.fr/fr (contact présent en pied de page).
Cordialement,

**Comment by infosteph** [comment]
@StopCovidFR  Si cette réponse vous convient, nous vous laissons fermer cet issue. Merci.
