### ISSUE TITLE
Le bouton ne génére le document qu'à la seconde pression 

### ISSUE THREAD

**Issue by gZaVia** [LAB-MI/deplacement-covid-19#116]
Changement par rapport à l'issue #40 
au premier clic rien 
au second le document est correctement généré.

iPhone 6
iOS 10.3.3
Safari

**Comment by mikaoelitiana** [comment]
Je ne reproduis pas sur la derniere version

**Comment by gZaVia** [comment]
En fait, je ne l'ai reproduit qu'une fois 
Je ferme.

**Comment by gZaVia** [comment]
.
