### ISSUE TITLE
Date of birth / not showing up on iPhone 

### ISSUE THREAD

**Issue by ahmadb-max** [LAB-MI/deplacement-covid-19#118]
Hello 
Lorsque j’essai de remplir le formulaire via iPhone (13.4.1) sur safari 
La date ne fait pas apparaître automatiquement les / 
Je ne peux donc pas éditer une attestation

**Comment by francoisefd78** [comment]
Bonjour, 
J'ai aussi ce problème non bloquant sur IOS 13.3.1.
Il existe un autre problème sur les champs date et lieu de naissance. 
- "date de naissance" n'est pas défini comme un champ date . Le champ n'accepte pas la valeur enregistrée.
- Lieu de naissance accepte la valeur par défaut de "date de naissance" au lieu du lieu. (voir copie d'écran)
![saisie automatique](https://user-images.githubusercontent.com/64466068/81068593-e9875380-8ee0-11ea-8df6-79e311adeacf.png)

**Comment by ahmadb-max** [comment]
Dans mon cas il s’avère que c’était l’extension Adblock qui posait problème
J’ai réinstaller Adblock 
Cela fonctionne désormais
