### ISSUE TITLE
Generation plusieurs Fichiers

### ISSUE THREAD

**Issue by cribuot** [LAB-MI/deplacement-covid-19#119]
Generation de plusieurs PDF en même temps.
Si on a un BEBE à transporter par exemple.

**Comment by waelausy** [comment]
à ma connaissance le bébé n'a pas besoin d'une attestation

**Comment by cribuot** [comment]
merci de la reponse

en fait dans le doute je la genere 
ce cas n est pas expliquer 

----- Mail original -----
De: "waelausy" <notifications@github.com>
À: "LAB-MI/deplacement-covid-19" <deplacement-covid-19@noreply.github.com>
Cc: "cribuot" <cribuot@free.Fr>, "Author" <author@noreply.github.com>
Envoyé: Dimanche 3 Mai 2020 16:26:06
Objet: Re: [LAB-MI/deplacement-covid-19] Generation plusieurs Fichiers (#119)





à ma connaissance le bébé n'a pas besoin d'une attestation

**Comment by infosteph** [comment]
Bonjour,
Comme le précise service-public.fr et gouvernement.fr, une seule attestation sur l'honneur suffit pour un adulte avec des enfants. En revanche, vous devez avoir avec vous la carte d'identité (ou livret de famille) de votre/vos enfants. Bien cordialement,
