### ISSUE TITLE
Envoi PDF vers telegram

### ISSUE THREAD

**Issue by babache** [LAB-MI/deplacement-covid-19#14]
Bonjour,

pour ceux qui souhaiteraient envoyer directement vers télégram le PDF j'ai faits cette modification dans le **certification.js**

Ajouter une fonction pour l'envoi (en renseignant avec les infos de votre bot) :
<pre>function sendBotTelegram(blobPDF){
    var token="VotreToken_ICI";
    var channel_id ="VotreID_ICI";
    var xhr = new XMLHttpRequest();
    var formData = new FormData();
    formData.append('chat_id', channel_id);
    formData.append('document', blobPDF, 'attestation'.pdf');
    xhr.open('POST', 'https://api.telegram.org/bot' + token + '/sendDocument', true);
    xhr.send(formData);
}
</pre>

Du coup ajouter l'appel (et commenter le téléchargement au pire) :
<pre>
$('#form-profile').addEventListener('submit', async event => {
  ....
  const pdfBlob = await generatePdf(getProfile(), reasons)
  sendBotTelegram(pdfBlob);
  //downloadBlob(pdfBlob, 'attestation.pdf')
  ...
}
</pre>

**Comment by infosteph** [comment]
Merci pour votre contribution !

**Comment by dsir-minute** [comment]
pas compris pourquoi on en aurait besoin !

**Comment by babache** [comment]
Peut être pour le générer à quelqu'un et l'envoyer facilement (et automatiquement) plutôt que par mail et faire une action manuelle ?

**Comment by philippeBron** [comment]
Merci pour votre proposition mais nous ne retenons pas.
Les personnes qui souhaitent transférer une attestation via l'application télégramme peuvent le faire en utilisant le pdf généré sur leur terminal.
Nous ne souhaitons pas intégrer ce générateur avec des produits tiers.
