### ISSUE TITLE
Consultation médicale : attestations périmées au bout d'une heure.

### ISSUE THREAD

**Issue by Shot2** [LAB-MI/deplacement-covid-19#147]
Les attestations générées via l'app (est-ce un simple renvoi vers un site ? ce n'est pas clairement indiqué) sont marquées "périmées" au bout d'une heure (60 minutes environ), notamment pour des déplacements médicaux.

Ceci est certes utile pour limiter les déplacements (pas d'examens médicaux longs ou loin de son domicile, p.ex. mammographie dans un centre départemental éloignée), et afin de décourager les consultations médicales dans un contexte de consommation excessive de services de santé, mais il serait encore plus dissuasif de préciser dans le label des champs que divers motifs de sortie (tous ?) sont aussi concernés par la limite de 60 minutes.

**Comment by bfontaine** [comment]
Cette limite n’a de toute façon aucune valeur légale, donc on voit mal l’intérêt de la dissuasion.

**Comment by Shot2** [comment]
10 jours plus tard, toujours le même problème.

**Consultation médicale** à 10h45.

En sortant de la consultation vers 12h10 (donc >1 heure plus tard) l'attestation est indiquée comme **périmée**.

**Solution** : désormais, imprimer des attestations papier, désinstaller l'app :)
