### ISSUE TITLE
Améliorer la prise en charge des navigateurs où le JavaScript est désactivé

### ISSUE THREAD

**Issue by DavidLibeau** [LAB-MI/deplacement-covid-19#15]
Ce formulaire fonctionne exclusivement avec JavaScript. Si aucune alternative pour le faire fonctionner sans cette technologie est possible, on peut tout de même améliorer le site pour les utilisateur·rice·s n'ayant pas JavaScript d'activé ou ayant des problèmes pour le chargement du script.

Par exemple, en utilisant des balises `<noscript>` pour informer l'utilisateur·rice que ce site web n'est pas utilisable sur son navigateur.

Un autre problème concerne le formulaire en lui même. Si le JavaScript est désactivé, les données personnelles de l'utilisateur·rice sont transmises au serveur. En effet, le formulaire HTML est paramétré pour envoyer les données en paramètres GET. On se retrouve avec une url de ce type : 
```
http://localhost:1234/index.html?firstname=Test&lastname=Test&birthday=01%2F01%2F1970&lieunaissance=Lyon&address=999+avenue+de+france&town=Paris&zipcode=75001&field-reason=sport&datesortie=2020-04-07&heure=12%3A05
```
On pourrait imaginer que le formulaire ne s'affiche carrément pas si le JavaScript n'est pas activé.

**Comment by JohnXLivingston** [comment]
Très bon point pour l'envoie du formulaire !

**Comment by babache** [comment]
Tout simplement on ajoute avant le **<form>**
<pre>
<noscript>
    <style>#form-profile{display:none}</style>
    <div class="alert alert-danger text-center"><b><u>/!\</u></b> Le javascript doit être activé pour générer l'attestation <b><u>/!\</u></b></div>
</noscript>
</pre>

**Comment by BlueskyFR** [comment]
Bonjour, je viens de faire une PR (#17) pour afficher un message d'avertissement renvoyant aux instructions permettant d'activer JavaScript dans le navigateur de l'utilisateur dans le cas-où celui-ci serait désactivé.
Je pense que cela permettra à plus de français d'utiliser le générateur.

**Comment by infosteph** [comment]
Bonjour, Merci pour votre proposition. Nous la retenons et allons l'utiliser.

**Comment by JohnXLivingston** [comment]
Ne faudrait-il pas aussi enlever la balise <form> et l'ajouter par javascript ?

**Comment by BlueskyFR** [comment]
> Ne faudrait-il pas aussi enlever la balise
> 
> et l'ajouter par javascript ?

de quelle balise parles-tu ? Dans tous les cas, il est préférable de passer par un `display: none` qui évite les ajouts et suppressions du DOM qui, eux, prennent plus de temps.
C'est ce que j'ai utilisé ici.

**Comment by BlueskyFR** [comment]
> > Bonjour, je viens de faire une PR (#17) pour afficher un message d'avertissement renvoyant aux instructions permettant d'activer JavaScript dans le navigateur de l'utilisateur dans le cas-où celui-ci serait désactivé.
> 
> Bonjour, Merci pour votre proposition. Nous la retenons et allons l'utiliser.

Super 😄

**Comment by JohnXLivingston** [comment]
> de quelle balise parles-tu ? Dans tous les cas, il est préférable de passer par un `display: none` qui évite les ajouts et suppressions du DOM qui, eux, prennent plus de temps.
> C'est ce que j'ai utilisé ici.


Je n'ai que survolé rapidement la PR. Si j'ai bien compris, elle ajoute un bandeau en haut pour avertir, mais laisse le formulaire en dessous. Donc quelqu'un qui n'a pas le javascript activé peut toujours envoyer le formulaire (clic sur le bouton ou touche entrée dans un champs). 
Je me trompe peut être, comme dit que j'ai que survolé le commit.

La solution que je préconise en pareil cas, c'est de retirer la balise <form> du fichier html. Et c'est le javascript qui transformera une balise div en form, ou qui ajoutera une balise form autour d'une div. Pas de balise form => pas de submit.

Une autre solution : enlever uniquement le bouton submit.

**Comment by JohnXLivingston** [comment]
Oh ! je viens de comprendre l'ambiguité... J'avais mis les chevron autour de 'form', et github ne l'a pas échappé... J'édite le message plus haut.

**Comment by BlueskyFR** [comment]
Du coup par défaut le formulaire n'est pas affiché (présent mais invisible) et le code JavaScript l'affichage dès le chargement de la page. Du coup, si la personne n'a pas JavaScript, le formulaire reste invisible.

**Comment by infosteph** [comment]
Bonjour, Les améliorations ont été apportées en tenant compte de vos recommandations @BlueskyFR. Je clos cet issue. Merci.
