### ISSUE TITLE
Clarifier la sélection simple ou multiple de motif(s) de sortie

### ISSUE THREAD

**Issue by SebastienTouze** [LAB-MI/deplacement-covid-19#18]
Bonjour, 

L'application permet la sélection de multiples motifs de sortie puisqu'elle utilise des checkbox. Néanmoins il est demandé de sélectionner "un motif de sortie". 

Remplacer "un motif" par "un ou des motif(s)" pour éviter toute confusion.

**Comment by infosteph** [comment]
Bonjour,

**Comment by infosteph** [comment]
Bonjour,
Vous avez tout à fait raison. Cette précision a été apportée. Elle sera livrée prochainement. Merci.

**Comment by infosteph** [comment]
Bonjour, La précision a été apportée. Je clos cet issue. Merci.
