### ISSUE TITLE
Problème de sécurité : des données sont stockées et jamais effacé sur le navigateur.

### ISSUE THREAD

**Issue by JohnXLivingston** [LAB-MI/deplacement-covid-19#19]
J'ai signalé ce bug sur twitter, monsieur Freyssinet disait qu'il allait le prendre en compte. Mais je vois que ça n'a toujours pas été fait 24h plus tard. Alors j'ouvre ce ticket. 

Il semble qu'il y ai un bout de code mort, qui devait servir à pré-remplir le formulaire en cas de re-visite. Sauf qu'il n'a pas été complètement décablé. À la génération du pdf, le formulaire complet est stocké dans le local storage du navigateur, et n'est jamais effacé.
Il ne sera pas non plus effacé si l'utilisateur efface tous ses cookies (il faut effacer toutes les données de site pour virer le localStorage). 

Je considère ce bug comme grave. Si quelqu'un utilise le générateur sur un ordinateur qui n'est pas le sien, ou se fait voler son terminal, une personne malveillante pourrait y trouver des données nécessaires et suffisantes pour une usurpation d'identité (nom, prénom, date et ville de naissance). 

Il faut absolument arrêter d'enregistrer ces données (ou alors demander l'accord, comme proposé ici : https://github.com/LAB-MI/deplacement-covid-19/issues/6 ). De plus, il faut absolument effacer les données présente si quelqu'un retourne sur la page. Et il faut communiquer pour prévenir les utilisateurs.
Plus vous attendez, plus vous exposez de gens.

J'ajoute que vous n'êtes pas à l'abris que quelqu'un de malveillant chez Incapsula ne récupère ces données (puisque je crois que vous incluez du javascript leur appartenant).

**Comment by infosteph** [comment]
Bonsoir, Je vous confirme que ce bug a bien été pris en compte et fera très rapidement l'objet d'une correction. Merci.

**Comment by JohnXLivingston** [comment]
Ok merci ! 
Ne pourriez vous pas communiquer par voie de presse, et conseiller d'utiliser la navigation privée pour générer le formulaire ? Je comprend que ce n'est pas bon pour l'image, mais ce serait beaucoup plus sérieux si l'information venait de vos services que par un article dans un journal d'investigation. 

Twitter  a communiqué sur un bug similaire il y a même pas une semaine. Et je trouve que c'est plutôt sage comme décision.

**Comment by infosteph** [comment]
Bonjour, Ce bug a été corrigé et la correction apportée par la nouvelle version (V1.1.0). Je clos donc cet issue. Merci.

**Comment by JohnXLivingston** [comment]
Bonjour,
Il reste à mon sens un problème : il faudrait effacer les données enregistrées les jours précédent dès l'ouverture de la page. Avec le correctif proposé, ce ne sera fait qu'à la génération du pdf.

D'autre part, il n'y a plus de raison de passer par le localStorage. Une façon rapide de changer ça serait de passer par une variable globale (dans saveProfile les localStorage.setItem sont juste à remplacer par des assignations, et idem dans getProfile). En l'état, si la lib de génération de PDF échoue, les données resteront dans le localStorage.
