### ISSUE TITLE
Translate the form in english

### ISSUE THREAD

**Issue by DavidLibeau** [LAB-MI/deplacement-covid-19#20]
As mentioned [on this official article](https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-derogatoire-et-justificatif-de-deplacement-professionnel), we can present an english document.

With the same idea, this form should also be translate in english for english users.

**Comment by infosteph** [comment]
Bonjour, A ce stade le passage en version numérique du document en langue anglaise n'a pas été retenu. Nous ne manquerons pas de réouvrir cet issue en cas d'arbitrage rendu en ce sens. Merci.
