### ISSUE TITLE
[A11Y] valeur d'un attr. for incorrecte 

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#21]
```
<label for="field-heure">Heure de sortie</label>
```
devrait être
```
<label for="field-heuresortie">Heure de sortie</label>
```

**Comment by ArnaudDelafosse** [comment]
Parfait, du coup si les références for/id des champs sont toutes correctes, les attributs aria-labelledby sur les <input> qui font référence à l'id de leur <label> respectifs sont inutiles et peuvent être retirés.

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0
