### ISSUE TITLE
[A11Y] Clarifier le caractère obligatoire de tous les champs et regrouper les cases à cocher

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#23]
Les 9 champs de saisie ont un attribut _required_, il est donc indispensable de les remplir avant de soumettre le formulaire. Cette information devrait figurer avant le formulaire (visuellement et dans le code).
Par ex. "Tous les champs sont obligatoires", "Tous les champs doivent être replis", etc.

Par ailleurs il serait bien de regrouper toutes les cases à cocher dans un élément _fieldset_ dont le premier enfant sera son titre dans un élément _legend_. 
Par ex.
```
<fieldset>
  <legend>Choisissez un ou plusieurs motifs de sortie</legend>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" name="field-reason" id="checkbox-travail" value="travail">
    <label class="form-check-label" for="checkbox-travail">Déplacements ...</label>
  </div>
  ...
</fieldset>
```

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0
