### ISSUE TITLE
[A11Y] Champs en erreur non exposés aux techno. d'assistance

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#24]
Quand un champ est en erreur (format de saisie incorrect ou absence de donnée pour un champ obligatoire), son état doit être exposé aux TA (technologies d'assistance). 
Pour cela deux options, soit :
- ajouter dynamiquement l'attribut `aria-invalid="true"` sur les `<input>` en erreur après soumission du formulaire et avant que le focus ne soit déplacé sur le 1er champ en erreur,
- ou mettre par défaut l'attribut `aria-invalid="false"` sur les champs et modifier la valeur à `"true"` quand c'est pertinent, après soumission du formulaire et avant que le focus ne soit déplacé sur le 1er champ en erreur.

**Comment by pli01** [comment]
L'option 1 a été ajoutée et livrée.
Merci @ArnaudDelafosse pour vos contributions

**Comment by ArnaudDelafosse** [comment]
Bonjour @pli01 
Désolé de revenir sur ce ticket fermé mais il semblerait que vous ayez ajouté l'attribut `aria-invalid="true"` par défaut sur les champs, et non après soumission du formulaire comme je vous le suggérais :

> ajouter dynamiquement l'attribut aria-invalid="true" sur les <input> en erreur **après soumission du formulaire** et avant que le focus ne soit déplacé sur le 1er champ en erreur,

Un champ vide (avant une première soumission du formulaire) n'est pas une erreur et ne devrait pas vocaliser "entrée invalide" aux utilisateurs de lecteurs d'écran à leur arrivée sur le champ.
Merci

**Comment by pli01** [comment]
En effet, une lecture trop rapide de votre proposition.
Nous prenons en compte pour une prochaine version.
N hésitez pas à nous proposer des PR en exemple, pour appliquer les bonnes pratiques (A11Y)
Merci @ArnaudDelafosse

**Comment by infosteph** [comment]
Bonjour @ArnaudDelafosse, La correction a été apportée. Bien cordialement,

**Comment by ArnaudDelafosse** [comment]
Bonjour @infosteph merci pour ces modifications.
Je ne vais pas vous cacher qu'il y a encore des améliorations possible concernant l'accessibilité du formulaire, tout particulièrement sur la gestion des erreurs pour ce qui est du plus impactant pour les utilisateurs (handicapés ou non).
Ma question est : pensez-vous avoir les ressources pour les traiter si je créé quelques nouveaux tickets ou est-ce que la durée de vie du formulaire limitée rend cela compliqué de votre coté ?
Merci

**Comment by infosteph** [comment]
@ArnaudDelafosse, Nous nous sommes engagés à étudier et, dans la mesure du possible, traiter les corrections liées à l'accessibilité. Donc oui, ouvrez s'il vous plaît les tickets liés. Nous regarderons au cas pas cas les corrections à apporter. Merci à vous.
