### ISSUE TITLE
[A11Y] Empêcher la vocalisation des pictos "validité" 

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#25]
Les pictogrammes contenus dans les `<span class="validity"></span>` sont des contenus CSS et peuvent être exposés aux TA dans certains cas. Or l'invalidité des champs est communiquée autrement, il faut donc les rendre "invisibles" aux lecteurs d'écran avec un attribut `aria-hidden="true"`.
Par ex.
`<span class="validity"></span>`
devient
`<span class="validity" aria-hidden="true"></span>`

Remarque : l'apparition de ces signes reste hasardeuse, dans Chrome j'ai des "âœ–" au lieu des croix et d'un point de vue purement UX, mettre des croix alors que l'utilisateur n'a pas encore saisi le moindre caractère dans le champ peut créer de la confusion chez certaines personnes. 
L'apparition d'une coche (_check_) quand le champ a été rempli est une petite _valeur ajoutée_ de réassurance mais qui n'a pas nécessairement besoin d'être exposée aux TA, selon moi vu qu'il y aura un control lors de la soumission du formulaire. L'attribut `aria-hidden="true"` sur le `<span>`reste donc pertinent.

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0
