### ISSUE TITLE
[A11Y] L'image du logo du Min. de l'intérieur n'a pas d'alternative textuelle

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#26]
L'image du logo du Min. de l'intérieur `MIN_Interieur_RVB.57f44120.svg` n'a pas d'alternative textuelle : l'attribut alt est vide. Or cette image contient du texte, ça n'est pas une image de décoration. 
L'attribut alt doit contenir le texte que contient l'image.
Par ailleurs comme l'image appelée est au format SVG, il est nécessaire d'ajouter un attribut `role="img"` à l'élément `<img>`.
Par ex.
`<img src="...MIN_Interieur_RVB.57f44120.svg" alt="" >`
devient
`<img src="...MIN_Interieur_RVB.57f44120.svg" role="img" alt="Ministère de l'intérieur. Liberté, égalité, fraternité." >`

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0
