### ISSUE TITLE
[A11Y] Apparition du message d'alerte navigateur Facebook qui n'est pas exposé aux TA.

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#27]
Si le message d'alerte n'est rendu visible qu'en lui retirant la classe CSS `.d-none` qui modifiera sa propriété `display` de `none` à `block`, les utilisateurs aveugles et certains utilisateurs malvoyants n'auront pas cette information, d'autant plus que le message se trouve en bas du DOM.

1. Il est préférable de le mettre au début du DOM, ce qui correspond à sa position à l'écran. La nature de l'information nécessite qu'elle puisse être accédée au plus vite par les lecteurs d'écran en lecture linéaire.
2. Pour qu'il soit vocalisé au moment il est rendu visible, il faut que l'élément qui a l'attribut `role="alert"` (un `<p>` plutôt qu'un `<div>`) soit vide par défaut et que le texte soit injecté dynamiquement.
Par ex.
`<div class="alert alert-danger d-none" role="alert" id="alert-facebook"> ATTENTION !! Vous utilisez actuellement le navigateur Facebook, ce générateur ne fonctionne pas correctement au sein de ce navigateur ! Merci d'ouvrir Chrome sur Android ou bien Safari sur iOS. </div>`
devient
`<p class="alert alert-danger d-none" role="alert" id="alert-facebook"></p>`
au chargement de la page, et le contenu est injecté dans le `<p>` quand cela est nécessaire.

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0
