### ISSUE TITLE
[A11Y] Valeur incorrecte pour l'attribut autocomplete (Code postal)

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#28]
La valeur de l'attribut `autocomplete` du champ _Code postal_ est incorrecte : `zipcode` n'existe pas mais `postal-code` est recommandée.
Voir les valeurs possibles ici https://www.w3.org/TR/WCAG21/#input-purposes
Par ex.
`<input type="number" id="field-zipcode" name="zipcode" autocomplete="zipcode" ...>`
devient
`<input type="number" id="field-zipcode" name="zipcode" autocomplete="postal-code" ...>`

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0
