### ISSUE TITLE
[A11Y] Design/UI Le contraste de certains textes est insuffisant

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#29]
Revoir certaines couleurs pour que le ratio de contraste entre le texte et la couleur qui l'entoure soit égal ou supérieur à 4,5 (4.5:1).
_Vérification possible dans l'Accessibility Inspector de Firefox, dans Colour Contrast Analyser de TPG, l'extension WCAG Color Contrast Checker, etc._

- [X] 1. texte de placeholder déplacé sous les champs lors de la saisie `<p class="exemple">ex.&nbsp;: Jean</p>`
- [X] 2. lien dans du texte comme `<a href="..." target="_blank">(liste sur gouvernement.fr)</a>`
- [ ] 3. survol (état _hover_) du lien dans le footer `<a class="num-08" href="tel:0800130000"> 0 800 130 000</a>`

**Comment by infosteph** [comment]
Bonjour Arnaud Delafosse, nous vous remercions pour ce travail de vérification et de mise en conformité au RGAA. Nous allons utiliser vos contributions pour améliorer notre formulaire dans une prochaine livraison.

**Comment by philippeBron** [comment]
Merci pour votre gros travail d'audit de ce service.
Nous avons pris en compte votre remarque dans la version 1.1.0

**Comment by ArnaudDelafosse** [comment]
Au nom des personnes qui en sont les premières à en bénéficier, merci pour votre réactivité et votre considération pour l'accessibilité.

Je me permet de vous signaler que le 3e point du ticket n'a pas été corrigé 

> survol (état hover) du lien dans le footer `<a class="num-08" href="tel:0800130000"> 0 800 130 000</a>`

Le bleu utilisé (#0056b3) a un ratio de contraste avec le fond noir de 2,9. Le ratio de contraste devrait être d'au moins 4,5. 
![image](https://user-images.githubusercontent.com/1129732/78907110-8db3e100-7a80-11ea-9205-38f4d80ab453.png)

**Comment by infosteph** [comment]
Merci pour votre vigilance. Nous sommes passés à côté de ce troisième point. Nous allons l'intégrer dans nos corrections.

**Comment by infosteph** [comment]
Correction apportée. Je ferme cet issue. Merci.
