### ISSUE TITLE
Nom de repository incorrect

### ISSUE THREAD

**Issue by Neamar** [LAB-MI/deplacement-covid-19#3]
Bonsoir !

Le nom du repository semble invalide, et mentionne le codiv-19 (coDiV)

Certes, 2019 n'est pas encore fini, mais espérons que le covid sera suffisant ;)

Le `package.json` semble hésiter entre les deux choix et mentionne coDiv et coVid :

https://github.com/LAB-MI/deplacement-covid-19/blob/40251245d29e8a03f8f88dcbfa85f4b12ab9dd0f/package.json#L15-L21

Le README quant à lui fait aussi référence au codiv-19.

(le repository peut être renommé depuis les settings, Github gérera automatiquement la redirection pour tout ceux qui ont encore l'ancien lien)

**Comment by franckentien** [comment]
Le repository est correctement corrigé mais pas le code source.
Je viens de faire une PR pour corriger ça.

**Comment by infosteph** [comment]
Merci. Nous allons apporter la correction.

**Comment by infosteph** [comment]
Bonjour, La correction a été apportée. Je clos cet issue.
