### ISSUE TITLE
Les champs date et heure ne devraient pas être autofill

### ISSUE THREAD

**Issue by doekia** [LAB-MI/deplacement-covid-19#31]
Lors de la 1ere utilisation, les champs date et heure sont vide, ils sont alors nourit de la date et l'heure du jour.
Lors d'une utilisation utérieur, google chrome utilise l'autofill pour remplir le formulaire avec les valeur précédement utilisées.
Ceci est assez important car par inattention les informations deviennent alors innapropriées lors d'un contrôle de police. C'est particulièrement dérangeant pour les personnes ayant peu de compétences en technologie.

**Comment by infosteph** [comment]
Bonjour, Nous avons pris en compte vos remarques et allons apporter les corrections nécessaires.

**Comment by infosteph** [comment]
Bonjour @doekia , les corrections ont été apportées. Je clos cet issue. Merci.
