### ISSUE TITLE
Sécurité : il est possible de falsifier l'heure à laquelle a été généré le PDF

### ISSUE THREAD

**Issue by aymericbouzy** [LAB-MI/deplacement-covid-19#36]
Actuellement, les données indiquées dans le QR code ne sont pas signées (elles sont en clair #8 ). Cela signifie que l'on peut créer des attestations qui _déclarent_ avoir été générées à une date donnée, sans que cela soit vrai. Il pourrait donc y avoir par exemple des applications mobiles qui génèreraient des attestation "à la volée" semblant avoir été générées par exemple une demi-heure au préalable, et qui seraient indiscernables par les forces de l'ordre d'une attestation réelle.

Une solution possible serait que le QR code contienne non pas le texte en clair, mais par exemple un [JWT](https://jwt.io), dont le contenu serait le même, mais qui aurait l'avantage d'être signé. La date d'émission serait définie par le serveur, sans possibilité d'altération. En utilisant un algorithme de signature asymétrique (comme par exemple RS256), il serait même possible de faire la vérification d'authenticité en mode offline (et instantanée), de manière complètement sécurisée.

Je peux faire une PR à ce sujet si vous le souhaitez.

**Comment by catwell** [comment]
> Une solution possible serait que le QR code contienne non pas le texte en clair, mais par exemple un JWT, dont le contenu serait le même, mais qui aurait l'avantage d'être signé. La date d'émission serait définie par le serveur, sans possibilité d'altération.

Ça ajouterait une dépendance au serveur au moment de la génération, et donc une possibilité de tracking.

Une amélioration serait de hasher le contenu actuel du QR Code, puis signer le hash, mais ça dépend toujours du serveur central.

Il y a des protocoles [faits pour ça](https://opentimestamps.org) qui ne dépendent pas d'une autorité centrale, mais la vérification est online.

**Comment by aymericbouzy** [comment]
> Il y a des protocoles faits pour ça qui ne dépendent pas d'une autorité centrale, mais la vérification est online.

Ca a l'air effectivement d'être une bien meilleure solution 😃

1.Est ce que le timestamp serait suffisamment petit pour être stocké dans le QR code ?
2. Qui payerait la transaction blockchain ?

**Comment by catwell** [comment]
1. En testant sur le site le fichier fait moins de 400 octets, la plus grande partie étant les URL des serveurs de timestamp.

2. Bonne question, avec le volume pas sûr que ça soit possible de s'appuyer entièrement sur les serveurs disponibles gratuitement, et donc il y aura un coût pour les transactions.

(Après je cite OpenTimestamps parce que je connais celui-là, mais il y a d'autres protocoles et/ou services de timestamping.)

**Comment by catwell** [comment]
La solution la plus simple que je vois avec des serveurs étatiques c'est de hasher le contenu avec un KDF (genre Argon2) et d'envoyer *juste* le digest (*pas* le salt) au serveur. Le serveur y rajoute une heure et signe.

Avantages :

- Vérifiable online
- Le serveur ne peut pas connaître le contenu de l'attestation (même avec du brute force)
- L'utilisateur ne peut pas falsifier l'heure

Inconvénient :

- Dépend d'un serveur
- Le serveur connaît au minimum l'IP source

**Comment by fcamblor** [comment]
> Après la question est : est-ce vraiment important d'éviter la falsification ?

Tellement d'accord avec ça...

J'ajouterais : n'est-ce pas se tirer une balle dans le pied que d'envoyer un contenu chiffré (même en toute bonne foi, sans possibilité par le serveur de revenir à l'information d'origine) à un serveur ?

N'est-ce pas ouvrir la boîte de pandore sur une mauvaise interprétation de ces informations par les réseaux sociaux ? (on est tracé par le gouvernement, toussa...)

**Comment by philippeBron** [comment]
Bonjour,
Nous avons choisi de jouer le jeu de la transparence au maximum en publiant le code source et en lassant la possibilité aux utilisateurs de vérifier le contenu du QR Code qui sera lu lors d'un contrôle.
Les attestations papier étant toujours valables, il me semble qu'il est toujours possible de remplis à la hâte la date et l'heure de sortie voire de la modifier.
Nous ne prétendons pas assurer un meilleur niveau de contrôle que les versions papier.

C'est pour cette raison que nous ne retenons pas votre proposition de sécuriser le QR Code.

**Comment by aymericbouzy** [comment]
C'est tout a fait valable comme argumentaire ! Je pense qu'il y a une différence assez fondamentale entre le format papier ou il est assez difficile de modifier quelque chose sous les yeux des forces de l'ordre, et le format numérique ou cela peut être vraiment indiscernable, mais je reconnais que ce serait beaucoup de complexité pour un gain limité.
