### ISSUE TITLE
Le téléchargement ne fonctionne pas sur firefox mobile

### ISSUE THREAD

**Issue by bbinet** [LAB-MI/deplacement-covid-19#37]
Erreur retournée au téléchargement dans firefox mobile: "Firefox ne peut pas télécharger ce type de fichier"

Alors que ça fonctionne bien sur Firefox sur un ordinateur.

Le problème a déjà été brièvement reporté dans le commentaire suivant:

_Originally posted by @guillemcanal in https://github.com/LAB-MI/deplacement-covid-19/issues/2#issuecomment-610300920_

**Comment by sylvestre** [comment]
Mozilla travaille sur le correctif:
https://github.com/mozilla-mobile/fenix/issues/9735
https://github.com/mozilla-mobile/android-components/issues/1159

**Comment by julienw** [comment]
Je viens de tester: ça fonctionne bien sur Firefox Release. Seule la version "Nightly" qui est une réécriture complète du logiciel a le souci.

**Comment by philippeBron** [comment]
merci pour ces précisions.
le problème est donc du côté de cette version nocturne du navigateur.

**Comment by infosteph** [comment]
Bonjour, le problème étant identifié sur cette version du navigateur, nous fermons cet issue. Merci.
