### ISSUE TITLE
Il est possible de générer une attestation incomplète.

### ISSUE THREAD

**Issue by vic60400** [LAB-MI/deplacement-covid-19#38]
Il semblerait que l'attribut `required` des inputs ne fonctionne pas. Aussi, il serait peut-être plus judicieux que `generate-btn` soit cliquable uniquement lorsque tous les champs sont renseignés.

**Comment by philippeBron** [comment]
merci pour votre retour.
nous notons votre issue qui est une amélioration du fonctionnement mais n'est pas bloquant pour l'utilisation du service.

**Comment by ArnaudDelafosse** [comment]
Attention avec cette suggestion qui pourrait détériorer l'accessibilité du formulaire pour les utilisateurs très malvoyants ou aveugles qui utilisent un lecteur d'écran.

Mettre un attribut HTML `disabled` sur le bouton de soumission du formulaire le rend "invisible" lors de la tabulation (navigation au clavier entre les éléments interactifs d'une page). De plus, d'un point de vue de l'UX (pour tout le monde), certaines personnes pourraient ne pas comprendre pourquoi le bouton ne fonctionne pas s'il n'est pas accompagné d'une explication.

Il est toutefois possible d'implémenter ce comportement de façon accessible, voir ici : https://twitter.com/arnauddelafosse/status/1142696289685200896

Mon avis est qu'il serait préférable de laisser à l'utilisateur la possibilité de soumettre le formulaire, même incomplet, avec une bonne gestion des erreurs. Cela reste hypothétiquement le comportement le plus attendu par la majorité des utilisateurs.

**Comment by pz38** [comment]
Egalement, quand on sélectionne aucun motifs la génération est possible.

**Comment by infosteph** [comment]
Bonjour @vic60400, Nous avons suivi vos recommandations et avons rendu impossible la génération du formulaire sans remplissage des champs. Bien cordialement,
