### ISSUE TITLE
ajouter date-heure dans le nom de fichier télécharger, pour mieux différencier  apres plusieurs jours d'attestation 

### ISSUE THREAD

**Issue by bdatchar** [LAB-MI/deplacement-covid-19#39]
changer le nom de fichier télécharger : attestation  par : 
attestion-covid19-{{date}-{heure}.pdf
ou si on veux allez plus loins pour ceux qui utilise un ordinateur pour une même familles
attestation-covid19-{{date}-{heure}-{nom}-{{Prenom}}.pdf
cela permet de faire des fichier unique.
pour mieux différencier dans un ordinateur ou smartphone, apres plusieurs jours de travail

**Comment by philippeBron** [comment]
merci pour votre proposition.
nous allons la prendre en compte dans un prochain correctif.
