### ISSUE TITLE
Le bouton ne génére absolument rien

### ISSUE THREAD

**Issue by gZaVia** [LAB-MI/deplacement-covid-19#40]
Le bouton ne génére absolument rien.
iPhone 6
iOS 10.3.3
Safari

**Comment by macmpi** [comment]
idem iPhone 4S, iOS 9.3.6, Safari

**Comment by infosteph** [comment]
Bonjour, Le support javascript pour IOS a-t-il été désactivé ?

**Comment by macmpi** [comment]
non l'option javascript (dans Réglages-Safari-avancé) est bien activée dans mon cas

**Comment by rujojean** [comment]
Bonjour , 
Sur Iphone 5c    IOS  10.3.3 pas de generation du tout en cliquant sur le bouton. Merci

**Comment by rujojean** [comment]
Bonjour , 
Meme probleme ( pas de generation du tout en cliquant sur le bouton) sur ipad IOS 9.3.5 Merci pour vos réponses

**Comment by marek-vanco** [comment]
Est ce que sur un autre navigateur avec les même données ça fonctionne ?

**Comment by rujojean** [comment]
Oui bien sur ca fonctionne sur ordinateur windows10 avec les memes données ( firefox) et sur Iphone 5s IOS 12.4.6 ( safari ) également avec les mêmes données .
Merci

**Comment by rujojean** [comment]
C'est une supposition mais je pense que sur Iphone IOS 10.3.3 et inférieur ca ne fonctionne pas ?

**Comment by rujojean** [comment]
N'est-ce pas une question de 32 ou 64 bits ?

**Comment by macmpi** [comment]
Probablement une dépendances sur des changements entre [webkit 604.x et ultérieurs](https://en.wikipedia.org/wiki/Safari_version_history) (603.x et avant)... 
Sauf erreur, sur iOS tous les navigateurs doivent utiliser webkit de tte façon.

**Comment by philippeBron** [comment]
Nous avons utilisé un outil de tests automatiques sur mobile pour vérifier la compatibilité. Le fournisseur nous annonce un iPhone 6 iOS 8.1. Mais nous n'avons pas la capacité de tester tous les terminaux.
Pouvez vous essayer avec un autre navigateur ?

**Comment by macmpi** [comment]
J'essaie de récupérer un vieux Chrome pour cet appareil.
Sinon, une possibilité de test via https://www.lambdatest.com/test-on-iphone-4s-mobile-browser-online

**Comment by philippeBron** [comment]
merci on a utilisé le même type de fournisseur. Peut-être que les résultats seront différents avec celui-là.
Dans le cas contraire, nous ne pourrons pas passer trop de temps à supporter les anciens mobiles (et surtout système car cela fonction avec un iPhone 6 et iOS 12).

**Comment by Rosa1955** [comment]
Je n’arrive pas à télécharger mon Attestation avec le QR code 
Il est mentionné ouvrir dans mais rien ne se passe en cliquant dessus sur IPhone SE

**Comment by macmpi** [comment]
testé avec Chrome 63.0.3239.73  (seule disponible sur iOS 9.3.6): même problème

**Comment by CorentinDy** [comment]
Testé avec Iphone 6S (iOs 13.3.X), avant la mise à jour 1.1.1 pas de PDF, mais depuis la mise à jour, le PDF se génère bien.

**Comment by tartinesKiller** [comment]
Ne fonctionne pas non plus sur Firefox Preview 4.2.1, sous Android 9

**Comment by rujojean** [comment]
Bonjour , J'avais un iphone 5c IOS 10.3.3 avec safari , je n'avais pas de génération de PDF .
J'ai trouvé un autre navigateur compatible avec IOS 10.3.3 ( il n'y en a plus beaucoup ) , il s'agit  de 
' BROWSER ' et la ca fonctionne correctement et le PDF est généré  . Merci à philippeBron qui a donné le début de solution . Cordialement

**Comment by guillaumezin** [comment]
> Ne fonctionne pas non plus sur Firefox Preview 4.2.1, sous Android 9

C'est un bug de Firefox Preview, cf. https://github.com/mozilla-mobile/android-components/issues/1159

**Comment by macmpi** [comment]
@philippeBron : semble être [un bug connu](https://bugs.webkit.org/show_bug.cgi?id=167341) de webkit.
Support for the "download" attribute was added in iOS 13.0.

[solution là](https://stackoverflow.com/questions/55760169/alternative-for-download-attribute-in-safari-ios)  par exemple :
The alternative is to open the file on the browser with the proper mime type, so it can show its content (and the user can then manually download it if needed).

**Comment by OSOTOKAITEN** [comment]
Bonjour.
Même problème sur PC WIN 7, WIN 10 avec IE11
Il faut changer de navigateur, et pourquoi pas d'OS, de marque de PC et autre.
Même chose pour les smartphones.

**Comment by Jennibara** [comment]
Bonjour, sur un téléphone Xiaomi avec Android, aucun document n'est généré. Je n'ai aucun autre problème de téléchargement. Que faire ? Merci.

**Comment by xela75013** [comment]
Pareil pour moi mobile Xiaomi 9t sous Android 10 et rien de généré dans le fichier download alors que JavaScript est bien activé.

**Comment by PaulPCIO** [comment]
Pareil Xiaomi + chrome

**Comment by oulalakesaco** [comment]
Aucune génération,
Téléphone Honor 7, Android 6, Firefox à jour
javascript en action
Que fait la police?

**Comment by jriboux** [comment]
Hello,

Idem sur un Android 10 avec Chrome à jour. 

Petit détail supplémentaire, au premier click rien n'est généré, si je click une seconde fois le pdf est bien téléchargé. 

Cordialement, 
Jonathan

**Comment by gZaVia** [comment]
(OP)
Bonjour,
je confirme le nouveau comportement décrit par jriboux :
Premier clic: rien, au second: c'est bon.
Je considère donc que le problème n'est plus même, et j'ouvre un nouveau ticket.
Merci à tous,
X.
iPhone 6
iOS 10.3.3
Safari
