### ISSUE TITLE
Analyse qualité et sécurité sur SonarCloud

### ISSUE THREAD

**Issue by jblievremont** [LAB-MI/deplacement-covid-19#41]
Dans un souci d'amélioration continue, il me semble intéressant d'appliquer des techniques d'analyse statique sur le code de l'application. SonarCloud offre des services d'analyse orientés qualité et sécurité, gratuits pour les projets open source.

Pour référence, voici [les résultats](https://sonarcloud.io/dashboard?id=jblievremont_deplacement-covid-19) d'une analyse configurée sur mon fork personnel.

**Comment by philippeBron** [comment]
Merci pour votre recommandation. Cependant ce service ayant vocation à être arrêté à la fin du confinement, nous ne souhaitons pas investir plus que nécessaire sur ce projet.
Nous avons en effet d'autres services tels que Candilib que nous continuons de faire évoluer.

**Comment by Sicault** [comment]
Veuillez me retirer de vos contacts !
Merci

Le ven. 10 avr. 2020 à 15:24, Philippe Bron <notifications@github.com> a
écrit :

**Comment by laurent-simon** [comment]
[@Sicault](https://github.com/LAB-MI/deplacement-covid-19/issues/41#issuecomment-612053457) : Relisez le mail que vous avez reçu, ou bien apprenez à lire.

C'est vous même qui avez souscrit au service de notification Github. Il vous vous appartient de vous désinscrire en désactivant votre demande de notification (sur le côté gauche de la page). Personne ne peut le faire pour vous!

**Comment by Sicault** [comment]
Je n'ai rien demandé

Le ven. 10 avr. 2020 à 17:55, laurent-simon <notifications@github.com> a
écrit :

**Comment by Sicault** [comment]
Et me reste quand même le droit de refuser vous mails
Quant à votre remarque gardez la pour vous !!

**Comment by Sicault** [comment]
Quand on répond ainsi, on change de métier.... Vous êtes à bout....

**Comment by philippeBron** [comment]
Madame,
Vous êtes sur un outil collaboratif de développent de logiciel. C'est cet outil qui vous envoie des mails pas les participants.
@laurent-simon ne fait pas partit de l'équipe du ministère de l'intérieur. Son commentaire certes un peu déplacé n'engage que lui.
Il semble que vous ne souhaitiez pas participer aux échanges et que vous ne soyez pas en mesure de désactiver les notifications (vous êtes la seule à pouvoir le faire).
Je ne peux de mon côté que bloquer vos interactions.
