### ISSUE TITLE
un seul check

### ISSUE THREAD

**Issue by LOOFFI** [LAB-MI/deplacement-covid-19#42]
Bonsoir,
comme des checkboxes sont utilisées et comme cela vous a déjà été signalé, vous avez ajouté dans l'intitulé qu'il était possible de choisir plusieurs motifs de sortie. Il aurait fallu et il faudrait plutôt adapter le code pour un seul check possible et donc un seul motif...

**Comment by LOOFFI** [comment]
La piste : des radios à la place...

**Comment by vic60400** [comment]
Une attestation peut comporter plusieurs motifs de sortie. Il faut donc des checkbox.

**Comment by ArnaudDelafosse** [comment]
@LOOFFI 
> Bonsoir,
> comme des checkboxes sont utilisées et comme cela vous a déjà été signalé, vous avez ajouté dans l'intitulé qu'il était possible de choisir plusieurs motifs de sortie. Il aurait fallu et il faudrait plutôt adapter le code pour un seul check possible et donc un seul motif...

- https://www.service-public.fr/particuliers/actualites/A13952  (_Un motif ou plusieurs ?_)
- http://www.leparisien.fr/societe/coronavirus-peut-on-cocher-plusieurs-cases-sur-l-attestation-de-deplacement-06-04-2020-8294778.php
- https://www.liberation.fr/checknews/2020/03/31/confinement-peut-on-cocher-plusieurs-cases-d-une-meme-attestation_1783710
- etc.

**Comment by philippeBron** [comment]
merci @ArnaudDelafosse. il est en effet possible et recommander d'indiquer plusieurs motifs pour limiter le nombre de sortie. Nous avons donc adapté le formulaire de saisie mais conservons le pdf officiel téléchargeable.

**Comment by LOOFFI** [comment]
Yep, au temps pour moi ! Effectivement en phase.

**Comment by Sicault** [comment]
Stop !!!Veuillez me retirer de vos contacts !
Merci
