### ISSUE TITLE
[A11Y] Régions / Landmarks ARIA

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#43]
Il y a déjà un `<header>` et un `<footer>` dans la page ; il est souhaitable qu’un `<main>` soit également présent et contiennent tout ce qui se trouve entre ces 2 régions. 
Ces _landmarks_ (régions) peuvent être utiles à certains utilisateurs de lecteur d’écran qui souhaitent naviguer rapidement dans la page.
Pour des raisons de compatibilités il est préférable de leur ajouter leur _landmark role_ ARIA respectif comme ce sont des enfants directs de `<body>`.

Suggestion :
```
<header class="wrapper">...</header>
...
<footer class="main-footer">...</footer>
```
deviendrait
```
<header role="banner" class="wrapper">...</header>
<main role="main">...</main>
<footer role="contentinfo" class="main-footer">...</footer>
```

**Comment by infosteph** [comment]
@ArnaudDelafosse , suggestion intégrée et livrée. Merci !
