### ISSUE TITLE
[A11Y] Rendre plus explicite le lien vers la liste des établissements ouverts

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#44]
Il est possible de rendre le lien vers la liste des établissements qui restent ouverts plus explicite en sortant les parenthèses du lien, et en indiquant la page vers laquelle il dirige les utilisateurs plutôt que le site. 
Par ex. « liste des commerces et établissements qui restent ouverts ». 

De plus, comme c’est un lien qui ouvre une nouvelle fenêtre, il faut le signaler comme cela a été fait dans les liens du footer, avec un attribut `title`. 

Suggestion :
`<label>... <a href="https://www.service-public.fr/particuliers/actualites/A13921" target="_blank">(liste sur gouvernement.fr)</a>.</label>`
deviendrait
`<label>... (<a href="https://www.service-public.fr/particuliers/actualites/A13921" title="Liste des commerces et établissements qui restent ouverts - nouvelle page" target="_blank">liste des commerces et établissements qui restent ouverts</a>).</label>`

**Comment by AliSoftware** [comment]
Note au cas où les mainteneurs feraient un copier coller trop rapide de votre suggestion de remplacement : une parenthèse en trop s'est glissée dans votre suggestion après la fin du tag ouvrant: `<a …>(liste …` devrait être `<a …>liste …` — puisque la parenthèse a déjà été ouverte à l'extérieur du lien (c'est tout l'objet de votre _issue_ 🙂)

**Comment by ArnaudDelafosse** [comment]
Merci @AliSoftware :) c'est corrigé.

**Comment by Sicault** [comment]
Stop !!!Veuillez me retirer de vos contacts !
Merci

Le jeu. 9 avr. 2020 à 23:20, Arnaud Delafosse <notifications@github.com> a
écrit :

**Comment by portaseb** [comment]
Sicault, merci pour tes messages.

Je pense que pour répondre à ton besoin, le plus simple est de plus suivre
le projet gitlab...

Bonne continuation

**Comment by Sicault** [comment]
Je n'ai rien demandé

**Comment by infosteph** [comment]
> Il est possible de rendre le lien vers la liste des établissements qui restent ouverts plus explicite en sortant les parenthèses du lien, et en indiquant la page vers laquelle il dirige les utilisateurs plutôt que le site.
> Par ex. « liste des commerces et établissements qui restent ouverts ».

Bonjour @ArnaudDelafosse , suggestion intégrée et livrée. Merci !
