### ISSUE TITLE
[A11Y] Design/UI Améliorer la perception des liens dans du texte

### ISSUE THREAD

**Issue by ArnaudDelafosse** [LAB-MI/deplacement-covid-19#45]
Il est généralement déconseillé de différencier visuellement des liens dans du texte uniquement par un changement de couleur. 
Même si ce procédé peut être rendu conforme au RGAA par une savante équation entre 3 taux de contraste (texte, lien et couleur de fond), cela reste peu accessible car problématique pour certains utilisateurs, qu’ils aient des problèmes de perception des couleurs ou non. 

Suggestion : utiliser l’affordance native du Web pour les liens, c’est-à-dire le soulignement, qui reste le moyen le plus sûr pour que le plus grand nombre d’utilisateurs perçoivent instantanément la présence de liens dans du texte (ou à proximité de texte qui n’est pas un lien).

Exemples problématiques sur la page :
1.	« Liste sur gouvernement.fr »
2.	« Github »
3.	dans le footer (voir capture, les liens ont un fond rouge).

![image](https://user-images.githubusercontent.com/1129732/78942091-3d0caa00-7ab9-11ea-81bf-b69a269629e7.png)

![image](https://user-images.githubusercontent.com/1129732/78942005-0cc50b80-7ab9-11ea-82d5-fc06c0d0d1b0.png)

**Comment by infosteph** [comment]
Bonjour @ArnaudDelafosse, Nous avons suivi vos recommandations et venons de livrer ces corrections. Merci pour votre contribution.

**Comment by ArnaudDelafosse** [comment]
Bonjour @infosteph vous voulez dire que c'est déjà en production ou que sera poussé lors de la prochaine MEP ? Je ne vois aucun lien souligné chez moi.

**Comment by infosteph** [comment]
Bonjour @ArnaudDelafosse , je pense que nous avons mal interprété vos recommandations. Nous avons rajouté le soulignement au survol alors que vous étiez visiblement en train de nous suggérer de mettre en place un soulignement constant afin de permettre le signalement des liens. Est-ce bien cela ?

**Comment by ArnaudDelafosse** [comment]
Bonjour @infosteph. C'est en effet la solution que je suggère.

**Comment by infosteph** [comment]
Bonjour @ArnaudDelafosse, nous avons ajouté le soulignement. Bien cordialement.
