### ISSUE TITLE
Ne pas autoriser de deuxième sortie une fois le formulaire rempli

### ISSUE THREAD

**Issue by loicortola** [LAB-MI/deplacement-covid-19#47]
Bonjour, bravo pour l'application et les efforts pour sauver les arbres :)

En revanche, il y a un petit biais : n'importe qui peut maintenant générer autant de dérogations qu'il le veut sitôt la première terminée.
Un petit moyen de ne pas autoriser la génération d'une autre dérogation dès qu'on en a fait une, ce serait top !
Comme tout le monde n'est pas sur FranceConnect, c'est peut-être overkill de sauver en DB, mais peut-être juste sauver la date dans le localStorage dans un premier temps permettrait de dissuader les malins...

**Comment by philippeBron** [comment]
Bonjour,
Rien n'empêche une personne de remplir à nouveau un formulaire papier juste après en avoir rempli un. Nous ne souhaitons pas que la version numérique dispose de plus de contrôle que la version papier.

**Comment by OSOTOKAITEN** [comment]
Bonjour.
Ce genre de vérification pénaliserait tous ceux qui sont oubliés, même dans des municipalités qui se baptisent "Villes" et qui s'aperçoivent, une fois rendus à destination que c'est fermé, pas encore ouvert, pas ce jour, etc, faute d'avoir pu trouver le renseignement dans la boîte aux lettres, sur internet, ou à la Mairie fermée 24/24 7/7 !

**Comment by philippeBron** [comment]
Suite à vos retours (10 votes et un commentaire allant dans le sens de notre réponse) nous clôturons cette issues
