### ISSUE TITLE
Format date de naissance

### ISSUE THREAD

**Issue by Dufau69004** [LAB-MI/deplacement-covid-19#48]
Bonjour,
La saisie et le format de la date de naissance ne sont pas contrôlés, exemple:
05/06//197

Passe est-il de verrouiller avec un bon format de date type
JJ/MM/AAAA

Merci
Bien à vous
Bernard

**Comment by philippeBron** [comment]
Bonjour, nous avons mis en place de outils d'aide à la saisie et non des mécanismes de contrôles des informations saisies.
Il se peut que nos aides soient défaillantes et/ou perfectibles. Nous prenons en compte certaines remarques en fonction de nos disponibilités.
Cependant, il n'est pas dans l'esprit de ce service d'être plus contraignant dans la saisie des champs que la version papier. Si vous vous apercevez d'une erreur de saisie, vous pouvez la corriger en générant à nouveau une attestation.

**Comment by infosteph** [comment]
Bonsoir, Sauf avis contraire de votre part, cet issue sera fermé demain soir.
