### ISSUE TITLE
Script Incapsula

### ISSUE THREAD

**Issue by DavidLibeau** [LAB-MI/deplacement-covid-19#5]
Dans la version mise en production, un script nommé `/_Incapsula_Resource` est ajouté en fin de document alors que le code source ne mentionne pas la présence de ce script.
![Capture-d’écran-deplacement-covid-19](https://user-images.githubusercontent.com/11574966/78592878-07ac5600-7846-11ea-9ea3-5e7e461829d4.jpg)

Je pense qu'il faudrait éclaircir la provenance de ce script et son objectif, et pourquoi celui-ci n'est pas présent dans le code source. S'il n'est pas utile, il faut le supprimer du site.

**Comment by loxK** [comment]
C'est expliqué dans la politique de confidentialité, c'est une protection DDOS.

Mais le code source ne l'ayant pas ça pose question sur la modification du code source entre celui publié ici et celui utilisé en production.

**Comment by jcolfej** [comment]
Il est possible que ce script soit ajouté à la volé par le serveur.
Cette technique est souvent utilisée avec les services anti-DDOS, tracking, etc...

**Comment by infosteph** [comment]
Bonjour, Ce script est effectivement rajouté à la volée par le service de protection Incapsula au moment de la diffusion (site couvert par un CDN). Si cette réponse vous convient, je vous propose de fermer ce ticket. Merci.
