### ISSUE TITLE
Parent isolés 

### ISSUE THREAD

**Issue by HyperionART** [LAB-MI/deplacement-covid-19#51]
Bonjour, 

il faudrait ajouter une fonctionnalité permettant de stipuler que nous sommes un parent isolé ainsi que les informations d'identification de l'enfant.

**Comment by philippeBron** [comment]
Bonjour, ce service ne peut pas ajouter de motifs ou d'information qui ne sont pas dans le formulaire pdf officiel.

**Comment by Sicault** [comment]
STOP

Le ven. 10 avr. 2020 à 12:30, HyperionART <notifications@github.com> a
écrit :

**Comment by Sicault** [comment]
Stop !!!Veuillez me retirer de vos contacts !
Merci

Le ven. 10 avr. 2020 à 15:30, Philippe Bron <notifications@github.com> a
écrit :
