### ISSUE TITLE
Application IOS

### ISSUE THREAD

**Issue by princefr** [LAB-MI/deplacement-covid-19#54]
Bonjour j'ai développé une application iOS qui suit le meme protocole que votre code pour générer une attestation dérogatoire de déplacement.
Le pdf comme le qrcode sont générés in app, aucune donnée n'est transmise à aucun serveur.
https://github.com/princefr/Confineup_Covid_IOS

Comme il est impossible de publier sur apple store des applications en lien avec le covid-19 quand on est pas affilié au gouvernement , il serait super de pouvoir avoir quelque chose de similaire.

**Comment by philippeBron** [comment]
Bonjour,
la version actuelle fonctionne sur iOS et ne nécessite pas d'installation. Nous avons fait le choix de ne pas passer par les magasins d'application.

**Comment by Sicault** [comment]
Veuillez me retirer de vos contacts !
Merci

Le ven. 10 avr. 2020 à 15:04, Prince ONDONDA <notifications@github.com> a
écrit :

**Comment by Nemhome** [comment]
Est-il envisageable de créer, sur iOS, non pas un PDF mais un [pass Wallet ](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html)? Ce serait plus lisible sur iOS qu'un PDF qui, des fois (manque de réseau, ...) se recharge avec une erreur ?

**Comment by Sicault** [comment]
Stop !!!Veuillez me retirer de vos contacts !
Merci

**Comment by philippeBron** [comment]
Ce service n'a pas vocation à perdurer. Nous limitons les développements qui ne sont pas strictement indispensables à son fonctionnement.
