### ISSUE TITLE
Indiquer dans le pdf généré qu'il peut y avoir plusieurs motifs

### ISSUE THREAD

**Issue by Sollies13** [LAB-MI/deplacement-covid-19#58]
Le pdf génère cette phrase "certifie que mon déplacement est lié au motif suivant".
A remplacer par "certifie que mon déplacement est lié au(x) motif(s) suivant(s)"

**Comment by pz38** [comment]
Déja indiqué dans le #38 :
Egalement, quand on sélectionne aucun motif la génération est possible.

**Comment by Sollies13** [comment]
J'indiquais ce problème car des personnes se sont vu infligées une amende car plusieurs motifs étaient indiqués au lieu d'un seul. Or il est bien légalement possible d'indiquer plusieurs motifs comme la page web le suggère maintenant. Mais cette information ne se retrouve pas dans le pdf généré.
Les forces de l'ordre ne voient que le pdf généré où il est indiqué "au motif suivant" et non "au(x) motif(s) suivant(s)"

**Comment by gissehel** [comment]
Je viens d'essayer sur la version actuelle, et je vois bien la marque du pluriel sur le document, ainsi que les différents motifs dans le code barre.

Je pense qu'il est possible de fermer cet Issue.

**Comment by philippeBron** [comment]
La remarque concerne le pdf. Ce dernier porte en effet la mention (cocher la case).
Il s'agit du document officiel que nous réutilisons pour y insérer les données que vous saisissez dans le formulaire web.
Nous ne pouvons malheureusement pas modifier ce document officiel. Nous avons déjà fait remonter ce point au service compétent et attendons une mise à jour.

**Comment by infosteph** [comment]
Bonjour,
