### ISSUE TITLE
La date de naissance et le code postal ne sont pas mis en cache de formulaire

### ISSUE THREAD

**Issue by Sollies13** [LAB-MI/deplacement-covid-19#59]
Le nom par exemple est mis en cache du formulaire. Il suffit de cliquer dans le champ vide pour faire apparaître la liste des noms déjà entrés une fois.
Ce n'est pas possible avec la date de naissance et le code postal. Problème du au format numérique ?

**Comment by philippeBron** [comment]
Le cache dont vous parlez est celui de votre navigateur. Nous avons supprimé la conservation des données du formulaire dans la dernière version.

**Comment by infosteph** [comment]
Bonjour,
En l'absence de commentaires supplémentaires, cet issue sera fermé ce soir.
