### ISSUE TITLE
Date de naissance

### ISSUE THREAD

**Issue by Piloup35** [LAB-MI/deplacement-covid-19#61]
Impossible de remplir correctement la date de naissance : le "/" n'apparait pas dans le clavier proposé (iPhone 7 sous IOS 13.4)

**Comment by pz38** [comment]
Je crois qu'il faut taper les 2 chiffres (exemple 09 pour 9) pour que le / apparaissent automatiquement.

**Comment by NerOcrO** [comment]
Que veux tu saisir comme date de naissance @Piloup35 ?

**Comment by Piloup35** [comment]
22/05/50

 

De : Fabien - MEFA <notifications@github.com>
Répondre à : LAB-MI/deplacement-covid-19 <reply@reply.github.com>
Date : samedi 11 avril 2020 à 12:44
À : LAB-MI/deplacement-covid-19 <deplacement-covid-19@noreply.github.com>
Cc : Piloup35 <jean-loup.hardy@laposte.net>, Mention <mention@noreply.github.com>
Objet : Re: [LAB-MI/deplacement-covid-19] Date de naissance (#61)

 

Que veux tu saisir comme date de naissance @Piloup35 ?

**Comment by Piloup35** [comment]
Pardon 22/05/1950

 

De : Fabien - MEFA <notifications@github.com>
Répondre à : LAB-MI/deplacement-covid-19 <reply@reply.github.com>
Date : samedi 11 avril 2020 à 12:44
À : LAB-MI/deplacement-covid-19 <deplacement-covid-19@noreply.github.com>
Cc : Piloup35 <jean-loup.hardy@laposte.net>, Mention <mention@noreply.github.com>
Objet : Re: [LAB-MI/deplacement-covid-19] Date de naissance (#61)

 

Que veux tu saisir comme date de naissance @Piloup35 ?

**Comment by philippeBron** [comment]
Bonjour,
en effet, le "/" est ajouté automatiquement lorsque vous saisissez 2 chiffres.

**Comment by Piloup35** [comment]
Bonjour,

Pas chez moi : taper 22051950 donne 222051950 et non pas 22/05/1950.

Encore un mystère de plus.

 

De : Philippe Bron <notifications@github.com>
Répondre à : LAB-MI/deplacement-covid-19 <reply@reply.github.com>
Date : samedi 11 avril 2020 à 14:40
À : LAB-MI/deplacement-covid-19 <deplacement-covid-19@noreply.github.com>
Cc : Piloup35 <jean-loup.hardy@laposte.net>, Mention <mention@noreply.github.com>
Objet : Re: [LAB-MI/deplacement-covid-19] Date de naissance (#61)

 

Bonjour,
en effet, le "/" est ajouté automatiquement lorsque vous saisissez 2 chiffres.
