### ISSUE TITLE
Condensat/signature des informations personnelles

### ISSUE THREAD

**Issue by pagedegeek** [LAB-MI/deplacement-covid-19#64]
On voit avec FoxTrace.io que des attestations avec les informations personnelles commencent à être partagées par les internautes les moins aguerris. Ils stockent le pdf dans des espaces de partage type dropbox ou autre. Souvent ils ne le savent que c'est partagé.

Peut être est-il possible de faire une signature crypto (SHA256) des informations personnelles "[prenom][nom][date-naissance][ville-naissance]" (pas forcément l'adresse tant que cette information n'est pas normalisée).
Alors dans l'attestation PDF (qui se retrouve des fois partagée) sera affiché uniquement la signature de ces informations (et non les informations en clair).
En cas de contrôle, l'agent demande ces informations à la personne contrôlée puis la signature est comparée avec le PDF/QRCODE.

L'exposition du PDF et des informations est donc diminuée.

Peut-être overkill ?

**Comment by pagedegeek** [comment]
Du coup, on a fait une PR pour exprimer l'idée. Mais ça nécessite une évolution de l'app. utilisée par les agents.

**Comment by philippeBron** [comment]
Merci pour votre proposition qui ne nécessitait cependant pas la mise en avant de votre produit.

Nous avons déjà répondu au sujet de la signature ou du chiffrement du QR Code (cf. issue #36).
Si certains partages leur PDF, les données sont également inscrites sur le formulaire. Chiffrer le QR Code n'apportera pas plus de sécurité.

**Comment by pagedegeek** [comment]
Sauf erreur, je crois qu'il s'agit de deux choses différentes. Ce qui est proposé dans notre PR c'est de n'intégrer qu'une signature d'une partie des données personnelles. Pas de les chiffrer. C'est clairement overkill. Les données personnelles ne se retrouveraient plus dans le PDF ni dans le QR. Uniquement une signature non réversible.
Au moment du contrôle, la méthode de signature est utilisée.
