### ISSUE TITLE
Bonjour

### ISSUE THREAD

**Issue by taillandier** [LAB-MI/deplacement-covid-19#68]
Nous avons iPhone 4s et iPhone6s
Le formulaire ne marche pas.
Il y en a assez de ces outils qui ne marchent que pour les friqués qui s’achètent du neuf.

**Comment by philippeBron** [comment]
Bonjour et merci pour votre retour.
Ce service fonctionne avec les iPhone 6 pour peu qu'ils soient à jour (iOS 10 ou supérieur).
Cette contrainte technique est indispensable pour que le service s'exécute sur votre mobile et qu'aucune donnée soit envoyée ou collectée par le ministère de l'intérieur.

**Comment by taillandier** [comment]
Merci pour votre réponse
J’ai IOS 13.3.1

**Comment by vic60400** [comment]
@philippeBron va falloir s'habituer à ce genre de commentaire désagréable depuis que vous avez mis le link github sur le form ^^

**Comment by infosteph** [comment]
Bonjour @taillandier , pourriez-vous s'il vous plaît nous préciser le navigateur utilisé ainsi que sa version ?

**Comment by pierles** [comment]
On peut contourner l'impossibilité de ces bons vieux iPhone 4S qui disposent cependant de l'application Mail
en générant le pdf sur un autre PC puis se l'envoyer.
l'iphone accèdera à ce pdf et le QR code sera lisible
Un peu lourd mais quand on tombe à court d'encre, c'est quand même plus rapide que de recopier la totalité du formulaire
