### ISSUE TITLE
Questions sur la license.

### ISSUE THREAD

**Issue by JohnXLivingston** [LAB-MI/deplacement-covid-19#7]
La license indique qu'on est libre de copier et modifier le code. Êtes-vous sûr que ce soit une bonne idée ? Ne risque-t-on pas de voir fleurir des sites malveillants imitant le site officiel, et enregistrant les données récoltées ?
Ou des applis plus ou moins bien/malveillantes.

D'ailleurs, en y réfléchissant... Le logo du ministère, je ne suis pas sûr que sa license soit libre.

**Comment by DavidLibeau** [comment]
Comme l'application est uniquement côté client, la fonction sauvegarder de n'importe quel navigateur web permet de dupliquer le site web. Ouvrir le code ne change pas grand chose.

**Comment by JohnXLivingston** [comment]
C'est une question juridique, non technique. Avec la licence telle qu'elle est, vous n'aurez aucun recours possible s'il y a des abus.
Si quelqu'un de malveillant décide de reprendre le code, avec le logo du ministère qui y est inclu, de le publier ailleurs en ajoutant une fonction sauvegardant les données, vous ne pourrez rien faire.

**Comment by JohnXLivingston** [comment]
La license me semble aussi en contradiction avec le paragraphe Copyright de cette page : https://www.interieur.gouv.fr/Infos-du-site/Mentions-legales (page dont le lien est derrière les mentions légales de https://media.interieur.gouv.fr/deplacement-covid-19/ )

**Comment by infosteph** [comment]
> D'ailleurs, en y réfléchissant... Le logo du ministère, je ne suis pas sûr que sa license soit libre.

Bonjour, Le logotype Marianne est effectivement déposé à l'INPI et depuis le 31 mars 2016, il fait partie des emblèmes protégés au titre de l’article 6 ter de la Convention de Paris.

**Comment by infosteph** [comment]
> Ceci étant, après une étude plus approfondie du dépôt, la question se pose pour la police Marianne, qui est une police de caractère qui est connue pour ne pas avoir été encore mise à disposition sous une licence libre.

La police Marianne est, elle aussi, déposée. Un travail est en cours au sein du Service d'Information du Gouvernement pour venir préciser ses conditions d'usage.

**Comment by Exagone313** [comment]
La licence dit :
```
The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.
```
Or le code original contient :
```
Copyright (c) Johann Pardanaud
```
Cette ligne a été supprimée de la licence.
Il faut que la ligne du nouveau Copyright soit ajouté au dessus :
```
Copyright (c) Ministère de l'intérieur
Copyright (c) Johann Pardanaud

Permission is hereby granted, free of charge, to any person obtaining a copy
...
```

**Comment by JohnXLivingston** [comment]
Ça me fait pensé qu'il me semble avoir vu que les licenses (pdf-lib, qrcode,.. ) n'étaient pas dans le javascript minifié. Je peux me tromper. Mais si elles sont effectivement retirées, il serait de bon ton de les y laisser (ça doit être une option pour Babel, mais je ne la connais pas par coeur)

**Comment by infosteph** [comment]
> l faut que la ligne du nouveau Copyright soit ajoutée au dessus :
> 
> ```
> Copyright (c) Ministère de l'intérieur
> Copyright (c) Johann Pardanaud
> ```

Nous avons apporté cette précision dans la licence.

**Comment by infosteph** [comment]
Bonjour, sauf avis contraire, cet issue sera fermé ce soir.  Merci.

**Comment by rgrunbla** [comment]
> La police Marianne est, elle aussi, déposée. Un travail est en cours au sein du Service d'Information du Gouvernement pour venir préciser ses conditions d'usage.

Bonjour, des nouvelles concernant ce passage?

La police d'écriture Marianne est toujours disponible dans ce dépôt, sous licence MIT. Il apparaît donc que la police est bien distribuée sous licence MIT, sans modification du dépôt ou précisions autres.

Merci
