### ISSUE TITLE
Problème de sécurisation des liens avec un target="_blank"

### ISSUE THREAD

**Issue by santacruz69** [LAB-MI/deplacement-covid-19#76]
Il faut ajouter un attribut rel="noreferrer" pour tous les liens externes cad www.interieur.goov.fr, www.service-public.fr et www.gouvernement.fr

**Comment by vic60400** [comment]
Etant donné que les liens cibles sont des liens de confiances. Aucun risque sécurité. (https://mathiasbynens.github.io/rel-noopener/)

**Comment by santacruz69** [comment]
Je sais pas si ont peut dire site de confiance pour les sites interieur.gouv.fr et gouvernement.fr, vu les résultats des tests par exemple sur mozilla observatory

**Comment by santacruz69** [comment]
C'est si simple a mettre en oeuvre que je ne vois pas le pb de le faire systématiquement

**Comment by infosteph** [comment]
Bonjour @santacruz69 , Nous vous remercions pour cette proposition. Nous ne la retiendrons pas. Les trois sites externes sont effectivement considérés comme des sites de confiance. En outre l'attribut n'est pas compatible avec certaines versions de navigateurs pour lesquels nous sommes encore tenus d'assurer une compatibilité. https://caniuse.com/#feat=rel-noopener . 
Merci
