### ISSUE TITLE
Problème potentiel de contraste sur le bouton mettre à jour

### ISSUE THREAD

**Issue by santacruz69** [LAB-MI/deplacement-covid-19#77]
<button id="reload-btn" class="btn btn-info">Mettre à jour</button>
Vérifier si le contraste est suffisant, cela me semble faible

**Comment by infosteph** [comment]
Bonjour,
Vous avez raison, le contraste est insuffisant sur ce bouton. Nous allons le modifier lors d'une prochaine livraison.

**Comment by santacruz69** [comment]
Merci de rendre service

**Comment by infosteph** [comment]
Bonjour @santacruz69 , Nous avons amélioré le contraste sur ce bouton. Bien cordialement,
