### ISSUE TITLE
Pas de validation HTML du formulaire

### ISSUE THREAD

**Issue by AntoineAugusti** [LAB-MI/deplacement-covid-19#79]
Bonjour,

Actuellement, **si vous ne remplissez aucun champ et que vous validez immédiatement le formulaire, vous aurez un PDF vide.**

Cette ligne du JS actuelle empêche la validation du formulaire, malgré la présence d'attributs `required`, de `pattern` etc.
https://github.com/LAB-MI/deplacement-covid-19/blob/61b778a27ede6d9f1185733a7237a52deec92a56/src/certificate.js#L237

Pour avoir la validation HTML, vous pouvez utiliser les méthodes `checkValidity` et `reportValidity` sur le `form` directement. Voir [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Constraint_validation_process)

```js
  if (!document.forms['form-profile'].checkValidity()) {
    document.forms['form-profile'].reportValidity()
    return
  }
```

**Comment by NyKo24** [comment]
PR #50 corrige le problème non ?

**Comment by AntoineAugusti** [comment]
La solution dans #50 duplique les fonctionnalités présentes dans les navigateurs et les erreurs sont présentées avec un alert. Je pense qu'on peut faire mieux.

**Comment by NyKo24** [comment]
C'est sur ;)
mais normalement tout les navigateurs le supporte de manière commune. (j'insiste sur le "normalement" :D)

**Comment by vic60400** [comment]
C'est en cours d'étude https://github.com/LAB-MI/deplacement-covid-19/issues/38

**Comment by infosteph** [comment]
Bonjour, Ce problème étant traité dans le cadre du #38, je clos cet issue.
