### ISSUE TITLE
Script Python pour générer le PDF sans browser?

### ISSUE THREAD

**Issue by Shohreh** [LAB-MI/deplacement-covid-19#80]
Bonjour,

Je n'ai pas les compétences techniques pour comprendre tout le fonctionnement, mais j'ai vu que la page référence trois morceaux de JavaScript*.

Si au final la page génère juste un PDF avec quelques champs et un QR (qui contient quoi, d'aillleurs ?), quelqu'un sait-il faire la même chose avec un simple script Python, afin de pouvoir générer le PDF sans avoir à utiliser un browser manuellement à chaque fois ?

Merci.

*<script type="application/ld+json">…</script>
<script src="/deplacement-covid-19/certificate.93fc9d96.js"></script>
<script async type="text/javascript" src="/_Incapsula_Resource?SWJIYLWA=719d34d31c8e3a6e6fffd425f7e032f3&ns=1&cb=1961350892"></script>

**Comment by Hopding** [comment]
Hello @Shohreh! 

I haven't worked on this project myself. But it appears to be using [`pdf-lib`](https://github.com/Hopding/pdf-lib) to generate PDFs:

https://github.com/LAB-MI/deplacement-covid-19/blob/61b778a27ede6d9f1185733a7237a52deec92a56/src/certificate.js#L5

`pdf-lib` is written in pure JavaScript, so it can run in any JavaScript environment. You asked about Python specifically, but if you're willing to write a Node script instead, then you can use the exact same `pdf-lib` code in your script that this project uses. (If you aren't familiar with [Node.js](https://nodejs.org/en/), it's a very popular runtime for executing JavaScript outside the browser).

Here's a nice tutorial explaining how to use `pdf-lib` in a Node script: http://thecodebarbarian.com/working-with-pdfs-in-node-js.html. The `pdf-lib` repo also contains many examples demonstrating how to do this: https://github.com/Hopding/pdf-lib#complete-examples.

**Comment by philippeBron** [comment]
Thank you @Hopding 
En complément de la réponse apportée, nous avons souhaité mettre à disposition du plus grand nombre un moyen de générer une attestation numérique. Javascript est supporté par un très grand nombre de navigateur contrairement à Python.
Cependant, @Shohreh ,vous pouvez réaliser une version Pyhton en suivant les indications de @Hopding 
Merci de fermer cette issue si la réponse vous convient.

**Comment by infosteph** [comment]
Bonjour, Sauf avis contraire de votre part, nous fermerons cet issue ce soir. Merci.

**Comment by teymour** [comment]
En complément de cette réponse, la lib python ``qrcode`` génère des qrcode quasi identique à ceux de la lib utilisée ici.

C'est ce que j'ai utilisé pour réaliser un générateur sans navigateur (en shell) : https://github.com/teymour/attestation-covid19
