### ISSUE TITLE
Orthographe de GitHub

### ISSUE THREAD

**Issue by AntoineAugusti** [LAB-MI/deplacement-covid-19#81]
https://github.com/LAB-MI/deplacement-covid-19/blob/61b778a27ede6d9f1185733a7237a52deec92a56/src/index.html#L259

En réalité c'est Git**H**ub 👼

**Comment by infosteph** [comment]
Bonjour, la correction sera apportée lors d'une prochaine livraison.

**Comment by infosteph** [comment]
Bonjour @AntoineAugusti, La correction a été apportée. Bien cordialement,
