### ISSUE TITLE
Un peu d'aide pour l'installation

### ISSUE THREAD

**Issue by Jefekoi** [LAB-MI/deplacement-covid-19#87]
Bonjour, j'ai télécharger le script 
Une fois décompressé je l'ai mis sur mon site (localhost) mais il ne génère pas de PDF 
Pourriez vous me mettre sur la voie où m'aider à bien l'installer

Merci pour votre aide.

**Comment by Jefekoi** [comment]
Personne pour m'aider ?

**Comment by razerbann** [comment]
Est-ce que tu peux décrire ton setup ? Comment tu as installé le projet ?
Est-ce que tu arrive à voir la page ?
Est-ce que tu as regardé la console du navigateur pour voir s'il y a des erreurs ?

**Comment by Jefekoi** [comment]
Bonjour et merci pour ta réponse

Et bien je suis débutant dans ce domaine.
J'ai téléchargé le script , décompressé puis je l'ai mis dans un dossier en Localhost (mamp pour MAC) 
Puis j'ai lancé index.html ... c'est tout ... Je penses que j'ai tout faux non ?

**Comment by razerbann** [comment]
Alors avant de commencer, tu dois avoir tous les outils nécessaires pour pouvoir installer et compiler la version que tu pourras utiliser dans ton serveur Web (Mamp ou autre).
Le code présent sur github est le code source et pas la version de production qu'un serveur Web peut servir/afficher.

Il faut installer NodeJS et NPM (https://nodejs.org/dist/v13.12.0/node-v13.12.0.pkg) ou tapes `brew install nodejs`si tu as Homebrew d'installé sur ton Mac.

Ensuite, tu clones ou tu télécharges le code source comme suit:
![Screenshot 2020-04-13 at 21 39 46](https://user-images.githubusercontent.com/7271421/79154179-68e8a200-7dcf-11ea-860a-ac6d18d1af6a.png)

Une fois téléchargé / cloné, (tu décompresses l'archive et) tu ouvres un terminal dans le répertoire créé (Shift + Clic droit -> New Terminal here).

Tu lances: `npm install` puis `PUBLIC_URL=/ npm run build`.
Cette dernière commande va créer une répertoire `dist` qui contient le code final que tu pourras mettre sur ton serveur Web.

Dans ton cas, comme tu utilises MAMP, tu peux copier le contenu du répertoire `dist` dans: /Applications/MAMP/htdocs et tu relances le serveur MAMP.

**Comment by Jefekoi** [comment]
Merci beaucoup Razerbann, je vais essayé demain (Mardi)

**Comment by razerbann** [comment]
Bon courage et n'hésites pas si tu as besoin d'aide.
(Aussi, n'oublies pas de fermer l'issue comme ça n'a aucun rapport avec le projet en lui même)

**Comment by Jefekoi** [comment]
Encore merci, ça ne marche pas 
J'ai très bien suivi ce que tu m'as dit , lors de l'installation j'ai eu des erreurs comme celui ci 👍 

`> fsevents@1.2.12 install /Users/eric/Downloads/deplacement-covid-19-master/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/eric/Downloads/deplacement-covid-19-master/node_modules/fsevents
gyp ERR! node -v v13.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
`

Puis une alerte sur 
``
⚠️  Please specify a publicURL using --public-url, otherwise schema assets won't be collected
⚠️  Please specify a publicURL using --public-url, otherwise schema assets won't be collected
`
Il y a bien eu la création du dossier DIST
Je l'ai glissé sur mon site mais là rien lorsque je veux valider la page ne fait rien

**Comment by razerbann** [comment]
Ah oui, effectivement j'ai oublié de te demander d'installer XCode CommandLine tools.
Dans le même terminal, tapes `xcode-select --install` puis entrer.
Une fois installé, relance les mêmes commandes décrites dans mon commentaire précédent.

**Comment by Jefekoi** [comment]
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by razerbann** [comment]
Essayes `xcode-select --reset`

**Comment by Jefekoi** [comment]
Je recommence de A à Z :)

**Comment by razerbann** [comment]
Potentiellement avec un `sudo`

**Comment by razerbann** [comment]
> Essayes `xcode-select --reset`

Potentiellement avec un sudo

**Comment by Jefekoi** [comment]
`iMac-de-Eric:deplacement-covid-19-master eric$ xcode-select --reset
xcode-select: error: --reset must be run as root (e.g. `sudo xcode-select --reset`).`

**Comment by razerbann** [comment]
Tapes: `sudo xcode-select --reset` dans ce cas.

**Comment by Jefekoi** [comment]
J'ai validé et il n'a rien fait même pas d'erreur

**Comment by razerbann** [comment]
Est-ce que tu as pu lancer les commandes décrites dans mon 2ème commentaires ?

**Comment by Jefekoi** [comment]
`-bash: cd: deplacement-covid-19: No such file or directory
iMac-de-Eric:deplacement-covid-19-master eric$ sudo xcode-select --reset
iMac-de-Eric:deplacement-covid-19-master eric$ `

**Comment by Jefekoi** [comment]
Yess Xcode est en cours d'installation :) 
`xcode-select --install`

**Comment by razerbann** [comment]
Parfait! Tu reprendras depuis le début alors et tu me diras si tu rencontres d'autres problèmes ;)

**Comment by Jefekoi** [comment]
ok

**Comment by Jefekoi** [comment]
Voilà j'ai refait la total et rien n'y change même résultat je valide ma feuille et rien pas de réponse.

On laisse tober pour aujourd'hui demain je vais refaire à zéro

En tout cas merci pour ton aide qui m'as déjà bien éclairé :)

**Comment by razerbann** [comment]
Est-ce qu'il y a des erreurs qui s'affichent quand tu lances `npm install` ou `PUBLIC_URL=/ npm run build` ?

**Comment by Jefekoi** [comment]
npm install

`iMac-de-Eric:deplacement-covid-19-master eric$ npm install
npm WARN bootstrap@4.4.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.4.1 requires a peer of popper.js@^1.16.0 but none is installed. You must install peer dependencies yourself.

audited 11452 packages in 7.456s

37 packages are looking for funding
  run `npm fund` for details

found 3 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
iMac-de-Eric:deplacement-covid-19-master eric$ `

**Comment by Jefekoi** [comment]
PUBLIC_URL=/ npm run build

Juste ce genre de souci 
`dist/certificate.552eacba.js.map                          ⚠️  2.75 MB    155ms
dist/certificate.552eacba.js                              ⚠️  1.24 MB    599ms`

**Comment by razerbann** [comment]
Utilises tu Chrome ?
Pourrais-tu ouvrir l'inspecteur et voir si tu as des erreurs sur la console ?
![Screenshot 2020-04-13 at 23 24 35](https://user-images.githubusercontent.com/7271421/79162668-f92de380-7ddd-11ea-8e2e-3c23dbb2ce1a.png)

**Comment by Jefekoi** [comment]
Non je n'utilise pas Chrome, j'ai Firefox et Safari

Bon là je suis HS

Bonne nuit et encore mille merci à toi

**Comment by Jefekoi** [comment]
Bonjour,

J'ai tout refais et rien n'y change le bouton ne fonctionne pas :(
capture d'écran ==> https://nsa40.casimages.com/img/2020/04/14/200414055829173161.png

**Comment by razerbann** [comment]
Bonjour!
Ce que tu afficher à droite n'est pas la console JS mais plutôt le code source de la page.
Quel navigateur utilises tu ?
Sur Safari, tu dois aller dans Safari > Préférences, cliques sur Avancées, puis sélectionnes « Afficher le menu Développement dans la barre des menus ».
Ensuite quand tu ouvres ta page, va dans le nouveau menu affiché en haut et cherche « Afficher la console JavaScript ».
Sur Firefox, tu ouvres la page et tu fais un clic droit puis « Examiner l'élément »
<img width="271" alt="Screenshot 2020-04-14 at 09 42 58" src="https://user-images.githubusercontent.com/7271421/79198920-7e43e780-7e34-11ea-82a4-b35b666a068c.png">
Et ensuite dans la fenêtre qui s'affiche, tu vas dans l'onglet console:
<img width="1678" alt="Screenshot 2020-04-14 at 09 43 07" src="https://user-images.githubusercontent.com/7271421/79198994-99165c00-7e34-11ea-9338-af551b7e17ba.png">
Maintenant tu clique sur le bouton générer et tu vois s'il y a des erreurs qui s'affichent sur la console JS ;)

**Comment by Jefekoi** [comment]
Bonjour Razerbann
Ha oui effectivement il y a des erreurs

https://nsa40.casimages.com/img/2020/04/14/20041410252356844.png

**Comment by razerbann** [comment]
Copies le contenu du répertoire `dist` dans `/Applications/MAMP/htdocs` et non le répertoire lui même.
Sinon, si tu préfère garder le répertoire, tu peux relancer la commande `PUBLIC_URL=/dist npm run build` et tu écrase le répertoire `/Applications/MAMP/htdocs/dist` par le nouveau.

**Comment by Jefekoi** [comment]
Wouaaaa ça marche quelques truc à modifier mais SUPER 

Question si je veux le mettre sur mon site web (uniquement pour ma femme et moi) je dois le mettre dans un dossier il ne marchera donc pas ???

**Comment by razerbann** [comment]
Voici un exemple qui t'aideras peut être:
- Tu lances `PUBLIC_URL=/covid npm run build`
- Tu copies le répertoire créé `dist` dans la racine de ton serveur Web (j'assume que tu utilises MAMP, pour Apache ça va être un peu plus compliqué) et tu le renommes en `covid` pour que ça corresponde à la valeur de `PUBLIC_URL`.
- Tu lances ton serveurs Web et tu dois pouvoir accéder au générateur d'attestations sur (http ou https)://TON_SITE_WEB/covid

**Comment by Jefekoi** [comment]
Super ça marche, je te remercie beaucoup c'est vraiment sympa ton aide et surtout j'ai appris beaucoup avec toi.
Merci Merci :)

**Comment by infosteph** [comment]
Bonjour @Jefekoi , Si l'aide apportée par @razerbann (que nous remercions) vous convient, pourriez-vous fermer cet issue ?  Merci.

**Comment by razerbann** [comment]
> Super ça marche, je te remercie beaucoup c'est vraiment sympa ton aide et surtout j'ai appris beaucoup avec toi.
> Merci Merci :)

Je t'en prie. Bonne continuation.
