### ISSUE TITLE
Typos in English translation

### ISSUE THREAD

**Issue by PeredurOmega** [LAB-MI/deplacement-covid-19#88]
The english version of the derogatory travel certificate controdicts the french version (and the website of the Minister of Home Affairs).

> "Travel between my home and my work, when remote work isn’t an option (you’ll also have to fill the work travel document) or work travels can’t be canceled."

Source: https://www.interieur.gouv.fr/Actualites/L-actu-du-Ministere/Attestation-de-deplacement-et-de-voyage

But on the Minsitry's website it's written:

> "Il n'est alors pas nécessaire de se munir de l'attestation dérogatoire (ci-dessus) en complément."

Source: https://www.service-public.fr/particuliers/actualites/A13952

Moreover, there is a typo in the english version: "commissionned" -> "commissioned".

This issue comes from : https://github.com/LAB-MI/deplacement-covid-19/issues/60#issuecomment-612809373.

**Comment by infosteph** [comment]
Hello,
We thank you for this report. We will report this error to the communications department of the Ministry of the Interior.
