### ISSUE TITLE
Typo in tooltip (french PDF)

### ISSUE THREAD

**Issue by PeredurOmega** [LAB-MI/deplacement-covid-19#89]
"Convcation judiciaire ou administrative" should be "Convocation judiciaire ou administrative".

![](https://user-images.githubusercontent.com/21149239/79105360-ca2d5880-7d70-11ea-897c-92b85fe4bd59.png)

This issue follows: https://github.com/LAB-MI/deplacement-covid-19/issues/60#issuecomment-612809373.

**Comment by philippeBron** [comment]
Thank you, we will transfer your remark to the right service.
We only use the PDF file and can't modify it.
