### ISSUE TITLE
Ajout du mode sombre, amélioration de l'accessibilité et support des écrans avec encoche

### ISSUE THREAD

**Issue by florentmorin** [LAB-MI/deplacement-covid-19#90]
Il est possible d'améliorer l'accessibilité et la compatibilité avec les iPhone sans casser l'existant et en conservant une pleine compatibilité.

Tout est détaillé dans la PR #83

**Comment by infosteph** [comment]
Bonjour @florentmorin, Nous nous sommes appuyé sur votre PR et avons ajouté le mode sombre. Merci pour votre contribution. Bien cordialement,

**Comment by florentmorin** [comment]
Merci 😁
