### ISSUE TITLE
Il n'est pas precisé si l'utilisateur doit entrer son adresse de domicile ou de résidence

### ISSUE THREAD

**Issue by numaru** [LAB-MI/deplacement-covid-19#97]
TL;PL: Un utilisateur peut avoir une adresse de **domicile** et de **résidence** différentes, mais il n'est pas précisé laquelle renseigner dans le formulaire. Il faudrait définir quelle adresse doit être utilisée et préciser/compléter le formulaire.

---

Il est demandé de présenter une carte d'identité lors d'un contrôle. C'est l'adresse du **domicile** qui se trouve sur celle-ci. C'est aussi l'adresse de **domicile** qui est, il me semble, en général utilisé lors d'une attestation sur l'honneur. On peut donc être tenté de croire que c'est cette adresse qu'il faut renseigner sur l'attestation.

Néanmoins, le formulaire généré par l'attestation indique qu'il est `fait a <l'adresse renseignée>`. Dans le cas ou l'utilisateur ne réside pas à son domicile, soit il manque un champ pour indiquer où a été généré le document, soit l'adresse à renseigner est forcement celle de résidence.

J'ai le sentiment que comme la **première version** du document papier ne contenait pas de motif de déplacement a restriction géographique, c'était l'adresse de **domicile** qui était attendue. Elle servait alors, au même titre que le lieu et la date de naissance à prouver l'identité. Alors que **maintenant**, il faudrait plutôt utiliser l'adresse de **résidence** pour permettre de contrôler la barrière kilométrique. Ce sentiment est grandement renforcé par le fait que lors d'un récent contrôle avec le fameux motif, l'agent m'a fait remarquer qu'il eût fallu indiquer l'adresse de **résidence**.

**Comment by gissehel** [comment]
J'imagine que si le ministère de l'intérieur veut prendre en compte ce besoin, le plus judicieux serait d'avoir un champs supplémentaire avec "**adresse de résidence si différente de celle du domicile**" (qui serait laissé vide pour la plupart des gens).

Comme cela, il n'y aurait ni ambiguïté pour le déclarant, ni pour les forces de l'ordre.

**Comment by gissehel** [comment]
(cela serait alors valable sur l'attestation électronique comme sur les autres formats)

**Comment by infosteph** [comment]
Bonjour, 

Comme nous avons pu le préciser dans plusieurs issues, nous n'avons pas la possibilité à notre niveau de changer ou adapter l'attestation générée car il s'agit d'un document officiel. Nous allons faire remonter ce manque de précision et nous vous invitons en en faire de même en utilisant les formulaires de contact des sites internet du Gouvernement et du ministère de l'Intérieur : 

- https://www.gouvernement.fr/contact/ecrire-au-premier-ministre

- https://www.interieur.gouv.fr/Contact/Ecrire-au-ministre-de-l-Interieur

En l'absence de commentaires supplémentaires, cet issue sera fermé ce soir.
